use std::collections::HashMap;

use quick_xml::Reader;
use quick_xml::events::Event;
use serde_json;
use trailbase_wasm::http::HttpError;

use crate::Assets;
use crate::db_kv::{kv_delete, kv_get, kv_set};
use crate::error::internal;

#[derive(serde::Serialize, serde::Deserialize)]
pub(crate) struct I18nEntry {
    pub(crate) id: String,
    pub(crate) value: String,
}

#[derive(serde::Serialize)]
pub(crate) struct I18nEditorResponse {
    pub(crate) default: Vec<I18nEntry>,
    #[serde(rename = "override")]
    pub(crate) override_: Vec<I18nEntry>,
}

const KV_OVERRIDE_PREFIX: &str = "i18n:";

pub(crate) fn override_key(locale: &str) -> String {
    return format!("{KV_OVERRIDE_PREFIX}{locale}");
}

pub(crate) fn parse_xliff(xml: &str) -> Result<Vec<(String, String)>, String> {
    let mut reader = Reader::from_str(xml);
    reader.config_mut().trim_text(true);

    let mut entries: Vec<(String, String)> = Vec::new();
    let mut current_id: Option<String> = None;
    let mut in_target: bool = false;
    let mut buf: Vec<u8> = Vec::new();

    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Start(e)) => {
                match e.name().as_ref() {
                    b"trans-unit" => {
                        current_id = e
                            .attributes()
                            .flatten()
                            .find(|a| a.key.as_ref() == b"id")
                            .and_then(|a| a.unescape_value().ok().map(|v| v.into_owned()));
                    }
                    b"target" => in_target = true,
                    _ => (),
                }
            }
            Ok(Event::Empty(e)) => {
                if e.name().as_ref() == b"trans-unit" {
                    current_id = e
                        .attributes()
                        .flatten()
                        .find(|a| a.key.as_ref() == b"id")
                        .and_then(|a| a.unescape_value().ok().map(|v| v.into_owned()));
                }
            }
            Ok(Event::Text(e)) => {
                if in_target
                    && let Some(id) = current_id.as_deref()
                {
                    let text = e.unescape().map_err(|err| err.to_string())?.into_owned();
                    if !text.is_empty() {
                        entries.push((id.to_string(), text));
                    }
                }
            }
            Ok(Event::CData(e)) => {
                if in_target
                    && let Some(id) = current_id.as_deref()
                {
                    let text = String::from_utf8_lossy(e.as_ref()).into_owned();
                    if !text.is_empty() {
                        entries.push((id.to_string(), text));
                    }
                }
            }
            Ok(Event::End(e)) => {
                match e.name().as_ref() {
                    b"trans-unit" => {
                        current_id = None;
                        in_target = false;
                    }
                    b"target" => in_target = false,
                    _ => (),
                }
            }
            Ok(Event::Eof) => break,
            Err(err) => {
                return Err(format!(
                    "XLIFF parse error at {}: {err}",
                    reader.buffer_position()
                ));
            }
            _ => (),
        }

        buf.clear();
    }

    return Ok(entries);
}

pub(crate) fn serialize_js_module(entries: &[(String, String)]) -> String {
    let mut out = String::with_capacity(64 + entries.len() * 32);
    out.push_str("// Auto-generated by wcauth. Do not edit.\n");
    out.push_str("export const templates = {\n");
    for (id, value) in entries {
        out.push_str("  ");
        out.push_str(&js_string(id));
        out.push_str(": ");
        out.push_str(&js_string(value));
        out.push_str(",\n");
    }
    out.push_str("};\n");
    return out;
}

pub(crate) fn read_override(locale: &str) -> Result<Option<Vec<(String, String)>>, HttpError> {
    let bytes = match kv_get(&override_key(locale))? {
        Some(b) if !b.is_empty() => b,
        _ => return Ok(None),
    };

    let map: HashMap<String, String> =
        serde_json::from_slice(&bytes).map_err(|e| internal(format!("invalid override JSON: {e}")))?;

    return Ok(Some(map.into_iter().collect()));
}

pub(crate) fn write_override(locale: &str, entries: &[(String, String)]) -> Result<(), HttpError> {
    let map: HashMap<&str, &str> = entries.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
    let bytes = serde_json::to_vec(&map).map_err(internal)?;
    kv_set(&override_key(locale), &bytes)?;
    return Ok(());
}

pub(crate) fn delete_override(locale: &str) -> Result<(), HttpError> {
    kv_delete(&override_key(locale))?;
    return Ok(());
}

pub(crate) fn merge_entries(
    default: &[(String, String)],
    overrides: &[(String, String)],
) -> Vec<(String, String)> {
    let override_map: HashMap<&str, &str> = overrides
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();

    let mut merged: Vec<(String, String)> = default
        .iter()
        .map(|(k, v)| {
            let value = override_map.get(k.as_str()).map_or(v.as_str(), |ov| *ov);
            return (k.clone(), value.to_string());
        })
        .collect();

    let default_keys: std::collections::HashSet<&str> =
        default.iter().map(|(k, _)| k.as_str()).collect();
    for (k, v) in overrides {
        if !default_keys.contains(k.as_str()) {
            merged.push((k.clone(), v.clone()));
        }
    }

    return merged;
}

pub(crate) fn load_default_xliff(locale: &str) -> Option<String> {
    let asset = Assets::get(&format!("xliff/{locale}.xlf"))?;
    return Some(String::from_utf8_lossy(&asset.data).into_owned());
}

/// Parse `<source>` text from each `<trans-unit>`, ignoring `<target>`.
/// English is the source language and has no dedicated xliff/{locale}.xlf;
/// use this to populate the read-only editor view for "en".
pub(crate) fn parse_xliff_sources(xml: &str) -> Result<Vec<(String, String)>, String> {
    let mut reader = Reader::from_str(xml);
    reader.config_mut().trim_text(true);

    let mut entries: Vec<(String, String)> = Vec::new();
    let mut current_id: Option<String> = None;
    let mut in_source = false;
    let mut buf: Vec<u8> = Vec::new();

    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Start(e)) => match e.name().as_ref() {
                b"trans-unit" => {
                    current_id = e
                        .attributes()
                        .flatten()
                        .find(|a| a.key.as_ref() == b"id")
                        .and_then(|a| a.unescape_value().ok().map(|v| v.into_owned()));
                }
                b"source" => in_source = true,
                _ => (),
            },
            Ok(Event::Text(e)) => {
                if in_source
                    && let Some(id) = current_id.as_deref()
                {
                    let text = e.unescape().map_err(|err| err.to_string())?.into_owned();
                    if !text.is_empty() {
                        entries.push((id.to_string(), text));
                    }
                }
            }
            Ok(Event::CData(e)) => {
                if in_source
                    && let Some(id) = current_id.as_deref()
                {
                    let text = String::from_utf8_lossy(e.as_ref()).into_owned();
                    if !text.is_empty() {
                        entries.push((id.to_string(), text));
                    }
                }
            }
            Ok(Event::End(e)) => match e.name().as_ref() {
                b"trans-unit" => {
                    current_id = None;
                    in_source = false;
                }
                b"source" => in_source = false,
                _ => (),
            },
            Ok(Event::Eof) => break,
            Err(err) => {
                return Err(format!(
                    "XLIFF parse error at {}: {err}",
                    reader.buffer_position()
                ));
            }
            _ => (),
        }

        buf.clear();
    }

    return Ok(entries);
}

fn js_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{2028}' => out.push_str("\\u2028"),
            '\u{2029}' => out.push_str("\\u2029"),
            '\0' => out.push_str("\\0"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    return out;
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
<file target-language="es" source-language="en" original="lit-localize-inputs" datatype="plaintext">
<body>
<trans-unit id="sgreet">
  <source>Hello</source>
  <target>Hola</target>
</trans-unit>
<trans-unit id="sbye">
  <source>Bye</source>
  <target></target>
</trans-unit>
<trans-unit id="snoTarget">
  <source>Source only</source>
</trans-unit>
<trans-unit id="sempty"/>
</body>
</file>
</xliff>"#;

    #[test]
    fn parse_xliff_extracts_targets_and_skips_empty() {
        let entries = parse_xliff(SAMPLE).expect("parse ok");
        assert_eq!(
            entries,
            vec![("sgreet".to_string(), "Hola".to_string())],
            "expected only non-empty target"
        );
    }

    #[test]
    fn serialize_js_module_emits_exports() {
        let entries = vec![("k".to_string(), "v \"quoted\"\nworld".to_string())];
        let js = serialize_js_module(&entries);
        assert!(js.starts_with("// Auto-generated"));
        assert!(js.contains("export const templates = {"));
        assert!(js.contains("\"k\":"));
        assert!(js.contains("\\\"quoted\\\""));
        assert!(js.contains("\\n"));
    }

    #[test]
    fn merge_entries_overrides_take_precedence() {
        let default = vec![
            ("a".to_string(), "A".to_string()),
            ("b".to_string(), "B".to_string()),
        ];
        let overrides = vec![
            ("a".to_string(), "A-override".to_string()),
            ("c".to_string(), "C-new".to_string()),
        ];
        let merged = merge_entries(&default, &overrides);
        let map: HashMap<String, String> = merged.into_iter().collect();
        assert_eq!(map.get("a"), Some(&"A-override".to_string()));
        assert_eq!(map.get("b"), Some(&"B".to_string()));
        assert_eq!(map.get("c"), Some(&"C-new".to_string()));
    }
}
